#!/bin/bash

# Copyright (c) 2019-2021 Robert LaRocca https://www.laroccx.com

# A shell script wrapper for Sonicwall netExtender.

script_version='2.0.5'
script_release='devel'	# options devel, beta, release

display_help_information() {
	cat <<-EOF_XYZ
		$(basename $0): unrecognized option '$1'
		Try 'netExtender --help' for more information.
	EOF_XYZ
};

display_version_information() {
	cat <<-EOF_XYZ
	$(basename $0) $script_version-$script_release
	Copyright (c) 2019-$(date +%Y) Robert LaRocca, https://www.laroccx.com
	License: The MIT License (MIT)
	Source Code: https://github.com/robertlarocca/linux-netextender-wrapper
	EOF_XYZ
};

main() {
	# source the system-wide configuration
	if [[ -f /etc/netextender.conf ]]; then
		source /etc/netextender.conf
	fi

	# source the user configuration, this overrides system-wide file
	if [[ -f $HOME/.netextender.conf ]]; then
		source $HOME/.netextender.conf
	fi

	# include additional user options
	local user_options="$@"

	case "$1" in
	-H | --help)
		display_help_information "$1"
		;;
	-V | --version)
		display_version_information
		;;
	*)
		$(which netExtender) \
			-u $username \
			-d $domain \
			-p $password \
			--dns-prefer-remote \
			--no-reconnect \
			$user_options \
			$server_address:$service_port
		;;
	esac
};

if [[ -x "$(which netExtender)" ]]; then
	main "$@" &
else
	echo "netExtender: command not found"
	exit 1
fi
