#!/bin/bash

# Copyright (c) 2019-2021 Robert LaRocca https://www.laroccx.com

# A shell script wrapper for Sonicwall netExtender.

script_version='2.2.0'
script_release='release' # options devel, beta, release

display_help_information() {
	cat <<-EOF_XYZ
		$(basename $0): unrecognized option '$1'
		Try 'netExtender --help' for more information.
	EOF_XYZ
}

display_version_information() {
	cat <<-EOF_XYZ
		$(basename $0) $script_version-$script_release
		Copyright (c) 2019-$(date +%Y) Robert LaRocca, https://www.laroccx.com
		License: The MIT License (MIT)
		Source Code: https://github.com/robertlarocca/linux-netextender-wrapper
	EOF_XYZ
}

main() {
	# Source the system-wide configuration
	if [[ -f /etc/netextender.conf ]]; then
		source /etc/netextender.conf 2>/dev/null
	fi

	# Source the user configuration which overrides the system-wide file
	if [[ -f $HOME/.netextender.conf ]]; then
		source $HOME/.netextender.conf
	fi

	# Include additional user options
	local user_options="$@"

	case "$1" in
	-H | --help)
		display_help_information "$1"
		;;
	-V | --version)
		display_version_information
		;;
	--dns)
		sudo systemd-resolve \
			--interface ppp0 \
			--set-dns "$dns_server1" \
			--set-dns "$dns_server2" \
			--set-domain "$dns_domain1" \
			--set-domain "$dns_domain2"
		;;
	*)
		# Connect VPN with user options
		$(which netExtender) \
			-u $username \
			-d $domain \
			-p $password \
			--dns-only-local \
			--no-reconnect \
			$user_options \
			$server_address:$service_port
		;;
	esac
}

if [[ -x "$(which netExtender)" ]]; then
	main "$@"
else
	echo "netExtender: command not found"
	exit 1
fi

# vi: syntax=sh ts=4 noexpandtab
